--------------------------------------------------------
-- Archivo creado  - martes-julio-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CO_CARGO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CO_CARGO" 
   (	"ID_CARGO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CO_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CO_EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER(10,0), 
	"NOMBRE_EMPLEADO" VARCHAR2(50 BYTE), 
	"APELLIDO_EMPLEADO" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"CEDULA" VARCHAR2(16 BYTE), 
	"FECHA_INGRESO" DATE, 
	"SALARIO" NUMBER, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CONTRASEÑA" VARCHAR2(70 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"ID_CARGO" NUMBER(10,0), 
	"IMAGEN" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CO_PERMISO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CO_PERMISO" 
   (	"ID_CARGO" NUMBER(10,0), 
	"ID_MODULO" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONF_MODULO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONF_MODULO" 
   (	"ID_MODULO" NUMBER(10,0), 
	"NOMBRE_MODULO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONF_MONEDA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONF_MONEDA" 
   (	"ID_MONEDA" NUMBER(10,0), 
	"NOMBRE_MONEDA" VARCHAR2(50 BYTE), 
	"CODIGO_INTERNACIONAL" VARCHAR2(3 BYTE), 
	"EQUIVALENCIA_DOLAR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(10,0), 
	"DESCRIPCION_CATEGORIA" VARCHAR2(100 BYTE), 
	"NOMBRE_CATEGORIA" VARCHAR2(35 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_CONVERSIONUNIDAD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" 
   (	"ID_UNIDADMEDIDA_ORIGEN" NUMBER(10,0), 
	"EQUIVALENCIA" BINARY_DOUBLE, 
	"ID_UNIDADMEDIDA_DESTINO" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_MATERIAPRIMA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_MATERIAPRIMA" 
   (	"ID_MATERIAPRIMA" NUMBER(10,0), 
	"NOMBRE_MATERIA" VARCHAR2(50 BYTE), 
	"DESCRIPCION_MATERIA" VARCHAR2(100 BYTE), 
	"COSTE" NUMBER, 
	"STOCK" BINARY_DOUBLE, 
	"STOCK_MINIMO" BINARY_DOUBLE, 
	"STOCK_MAXIMO" BINARY_DOUBLE, 
	"IMAGEN" VARCHAR2(100 BYTE), 
	"ID_CATEGORIA" NUMBER(10,0), 
	"ID_PROVEEDOR" NUMBER(10,0), 
	"ID_MONEDA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_PRODUCTO" 
   (	"CODIGO_BARRA" VARCHAR2(20 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(35 BYTE), 
	"DESCRIPCION_PRODUCTO" VARCHAR2(100 BYTE), 
	"PRECIO" NUMBER, 
	"STOCK" BINARY_DOUBLE, 
	"STOCK_MAXIMO" BINARY_DOUBLE, 
	"STOCK_MINIMO" BINARY_DOUBLE, 
	"IMAGEN" VARCHAR2(80 BYTE), 
	"ID_MONEDA" NUMBER(10,0), 
	"ID_CATEGORIA" NUMBER(10,0), 
	"ID_UNIDADMEDIDA" NUMBER(10,0), 
	"ESTANTERIA" NUMBER(10,0), 
	"GAVETA" NUMBER(10,0), 
	"ID_ENVOLTORIO" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"ES_EMPRESA" VARCHAR2(1 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CONTACTO_PERSONA" VARCHAR2(100 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(60 BYTE), 
	"IMAGEN" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_TIPOUNIDADMEDIDA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_TIPOUNIDADMEDIDA" 
   (	"ID_TIPO" NUMBER(10,0), 
	"NOMBRETIPO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_UBICACION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_UBICACION" 
   (	"ESTANTERIA" NUMBER(10,0), 
	"GAVETA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IN_UNIDADMEDIDA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."IN_UNIDADMEDIDA" 
   (	"ID_UNIDADMEDIDA" NUMBER, 
	"NOMBREUNIDADMEDIDA" VARCHAR2(40 BYTE), 
	"ID_TIPO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CO_CARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CO_CARGO" ON "SYSTEM"."CO_CARGO" ("ID_CARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_EMPLEADO" ON "SYSTEM"."CO_EMPLEADO" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CO_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CO_ROL" ON "SYSTEM"."CO_PERMISO" ("ID_CARGO", "ID_MODULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONF_MODULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CONF_MODULO" ON "SYSTEM"."CONF_MODULO" ("ID_MODULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CO_MONEDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CO_MONEDA" ON "SYSTEM"."CONF_MONEDA" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_CATEGORIA" ON "SYSTEM"."IN_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_CONVERSIONUNIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_CONVERSIONUNIDAD" ON "SYSTEM"."IN_CONVERSIONUNIDAD" ("ID_UNIDADMEDIDA_ORIGEN", "ID_UNIDADMEDIDA_DESTINO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_MATERIAPRIMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_MATERIAPRIMA" ON "SYSTEM"."IN_MATERIAPRIMA" ("ID_MATERIAPRIMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_PRODUCTO" ON "SYSTEM"."IN_PRODUCTO" ("CODIGO_BARRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_PROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_PROVEEDOR" ON "SYSTEM"."IN_PROVEEDOR" ("ID_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_TIPOUNIDADMEDIDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_TIPOUNIDADMEDIDA" ON "SYSTEM"."IN_TIPOUNIDADMEDIDA" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_UBICACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_UBICACION" ON "SYSTEM"."IN_UBICACION" ("ESTANTERIA", "GAVETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IN_UNIDADMEDIDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_IN_UNIDADMEDIDA" ON "SYSTEM"."IN_UNIDADMEDIDA" ("ID_UNIDADMEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CO_CARGO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CO_CARGO" MODIFY ("ID_CARGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_CARGO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_CARGO" ADD CONSTRAINT "PK_CO_CARGO" PRIMARY KEY ("ID_CARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CO_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("NOMBRE_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("APELLIDO_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("FECHA_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("SALARIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("ID_CARGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_EMPLEADO" ADD CONSTRAINT "PK_EMPLEADO" PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CO_PERMISO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CO_PERMISO" MODIFY ("ID_CARGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_PERMISO" MODIFY ("ID_MODULO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CO_PERMISO" ADD CONSTRAINT "PK_CO_ROL" PRIMARY KEY ("ID_CARGO", "ID_MODULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONF_MODULO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONF_MODULO" MODIFY ("ID_MODULO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MODULO" MODIFY ("NOMBRE_MODULO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MODULO" ADD CONSTRAINT "PK_CONF_MODULO" PRIMARY KEY ("ID_MODULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONF_MONEDA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONF_MONEDA" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MONEDA" MODIFY ("NOMBRE_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MONEDA" MODIFY ("CODIGO_INTERNACIONAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MONEDA" MODIFY ("EQUIVALENCIA_DOLAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONF_MONEDA" ADD CONSTRAINT "PK_CO_MONEDA" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CATEGORIA" MODIFY ("DESCRIPCION_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CATEGORIA" MODIFY ("NOMBRE_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CATEGORIA" ADD CONSTRAINT "PK_IN_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_CONVERSIONUNIDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" MODIFY ("ID_UNIDADMEDIDA_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" MODIFY ("EQUIVALENCIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" MODIFY ("ID_UNIDADMEDIDA_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" ADD CONSTRAINT "PK_IN_CONVERSIONUNIDAD" PRIMARY KEY ("ID_UNIDADMEDIDA_ORIGEN", "ID_UNIDADMEDIDA_DESTINO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_MATERIAPRIMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("ID_MATERIAPRIMA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("NOMBRE_MATERIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("DESCRIPCION_MATERIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("COSTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("STOCK_MINIMO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("STOCK_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" ADD CONSTRAINT "PK_IN_MATERIAPRIMA" PRIMARY KEY ("ID_MATERIAPRIMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("CODIGO_BARRA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("DESCRIPCION_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("STOCK_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("STOCK_MINIMO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("ID_UNIDADMEDIDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("ESTANTERIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("GAVETA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" MODIFY ("ID_ENVOLTORIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "PK_IN_PRODUCTO" PRIMARY KEY ("CODIGO_BARRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("ES_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("CONTACTO_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_PROVEEDOR" ADD CONSTRAINT "PK_IN_PROVEEDOR" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_TIPOUNIDADMEDIDA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_TIPOUNIDADMEDIDA" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_TIPOUNIDADMEDIDA" MODIFY ("NOMBRETIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_TIPOUNIDADMEDIDA" ADD CONSTRAINT "PK_IN_TIPOUNIDADMEDIDA" PRIMARY KEY ("ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_UBICACION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_UBICACION" MODIFY ("ESTANTERIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_UBICACION" MODIFY ("GAVETA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_UBICACION" ADD CONSTRAINT "PK_IN_UBICACION" PRIMARY KEY ("ESTANTERIA", "GAVETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IN_UNIDADMEDIDA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_UNIDADMEDIDA" MODIFY ("ID_UNIDADMEDIDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_UNIDADMEDIDA" MODIFY ("NOMBREUNIDADMEDIDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_UNIDADMEDIDA" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."IN_UNIDADMEDIDA" ADD CONSTRAINT "PK_IN_UNIDADMEDIDA" PRIMARY KEY ("ID_UNIDADMEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CO_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CO_EMPLEADO" ADD CONSTRAINT "FK_20" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "SYSTEM"."CO_CARGO" ("ID_CARGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CO_PERMISO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CO_PERMISO" ADD CONSTRAINT "FK_43" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "SYSTEM"."CONF_MODULO" ("ID_MODULO") ENABLE;
  ALTER TABLE "SYSTEM"."CO_PERMISO" ADD CONSTRAINT "FK_57" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "SYSTEM"."CO_CARGO" ("ID_CARGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IN_CONVERSIONUNIDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" ADD CONSTRAINT "FK_111" FOREIGN KEY ("ID_UNIDADMEDIDA_ORIGEN")
	  REFERENCES "SYSTEM"."IN_UNIDADMEDIDA" ("ID_UNIDADMEDIDA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_CONVERSIONUNIDAD" ADD CONSTRAINT "FK_114" FOREIGN KEY ("ID_UNIDADMEDIDA_DESTINO")
	  REFERENCES "SYSTEM"."IN_UNIDADMEDIDA" ("ID_UNIDADMEDIDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IN_MATERIAPRIMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" ADD CONSTRAINT "FK_158" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "SYSTEM"."IN_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" ADD CONSTRAINT "FK_161" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "SYSTEM"."IN_PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
  ALTER TABLE "SYSTEM"."IN_MATERIAPRIMA" ADD CONSTRAINT "FK_164" FOREIGN KEY ("ID_MONEDA")
	  REFERENCES "SYSTEM"."CONF_MONEDA" ("ID_MONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IN_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "FK_131" FOREIGN KEY ("ID_MONEDA")
	  REFERENCES "SYSTEM"."CONF_MONEDA" ("ID_MONEDA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "FK_134" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "SYSTEM"."IN_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "FK_137" FOREIGN KEY ("ID_UNIDADMEDIDA")
	  REFERENCES "SYSTEM"."IN_UNIDADMEDIDA" ("ID_UNIDADMEDIDA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "FK_144" FOREIGN KEY ("ESTANTERIA", "GAVETA")
	  REFERENCES "SYSTEM"."IN_UBICACION" ("ESTANTERIA", "GAVETA") ENABLE;
  ALTER TABLE "SYSTEM"."IN_PRODUCTO" ADD CONSTRAINT "FK_167" FOREIGN KEY ("ID_ENVOLTORIO")
	  REFERENCES "SYSTEM"."IN_MATERIAPRIMA" ("ID_MATERIAPRIMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IN_UNIDADMEDIDA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."IN_UNIDADMEDIDA" ADD CONSTRAINT "FK_107" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "SYSTEM"."IN_TIPOUNIDADMEDIDA" ("ID_TIPO") ENABLE;
